save point week2

diff --git a/.bin/run_module b/.bin/run_module
--- a/.bin/run_module
+++ b/.bin/run_module
@@ -142,12 +142,13 @@ main() {
         quiz_file="$1"
         if [[ $response -eq 0 ]]; then
             start_time=$(date +%Y-%m-%dT%H:%M:%S)
-            if ! quiz "$quiz_file"; then
-                echo "Quiz failed! Contact instructor module={$module}."
-            else
-                mark_completed "$module" "$start_time" "quiz"
-                echo "Quiz completed successfully!"
-            fi
+            (cd ${TOP_DIR}/../.python && ./run_quiz.sh $quiz_file)
+            #if ! quiz "$quiz_file"; then
+            #    echo "Quiz failed! Contact instructor module={$module}."
+            #else
+            #    mark_completed "$module" "$start_time" "quiz"
+            #    echo "Quiz completed successfully!"
+            #fi
         fi
     }
 
