cosmetic

diff --git a/.bin/start b/.bin/start
--- a/.bin/start
+++ b/.bin/start
@@ -1,12 +1,34 @@
-#!/usr/bin/env -S bash -e
+#!/bin/bash
+
+export TOP_DIR="$(dirname "$(realpath "$0")")"
+export PROFILE_DB="${TOP_DIR}/../.db/profile.sqlite3"
+export TRACKER_FILE="${HOME}/.lab_tracker"
+export DEBUG="${TOP_DIR}/debug.txt"
+# Reference start date (week 1)
+# ---- EXTRACT STUDENT ID ----
+if [[ -f "$PROFILE_DB" ]]; then
+  export STUDENT_ID=$(sqlite3 "$PROFILE_DB" "SELECT id FROM students LIMIT 1;")
+  export FIRSTNAME=$(sqlite3 "$PROFILE_DB" "SELECT firstname FROM students LIMIT 1;")
+  export LASTNAME=$(sqlite3 "$PROFILE_DB" "SELECT lastname FROM students LIMIT 1;")
+  if [[ -z "$STUDENT_ID" ]]; then
+    echo "[!] student_id not found in $PROFILE_DB"
+    exit 1
+  fi
+else
+  echo "[!] Profile database not found at $PROFILE_DB"
+  exit 1
+fi
+START_DATE="2025-06-13"
 if [ -z "$TMUX" ]; then
     exec tmux new-session "$0"
 fi
-export TOP_DIR="$(dirname "$(realpath "$0")")"
-export TRACKER_FILE="${HOME}/.lab_tracker"
-export DEBUG="${TOP_DIR}/debug.txt"
 
-
+# Today's date
+export TODAY=$(date +%Y-%m-%d)
+# Get number of days since start
+export DAYS_ELAPSED=$(( ( $(date -d "$TODAY" +%s) - $(date -d "$START_DATE" +%s) ) / 86400 ))
+# Week number (week 1 starts at 0 days)
+export WEEK_NUMBER=$(( (DAYS_ELAPSED / 7) + 1 ))
 
 INTERRUPTED=0
 yesno() {
@@ -39,9 +61,9 @@ on_sigint_top() {
 
 run_module_start() {
     # To reset tracker file, uncomment the next line
-    #RESET_PROGRESS=1 run_module
+    RESET_PROGRESS=1 run_module $1
 
-    run_module $1
+    #run_module $1
 }
 
 trap 'on_sigint_top' SIGINT
@@ -68,13 +90,12 @@ main() {
 		OPTIONS+=("$i" "${modules[$i]}")
 	    done
 	    # Show dialog menu
-        export TERM=xterm-256color
         selection=$( \
-          DIALOGRC=${TOP_DIR}/dialogrc \
+          TERM=xterm-256color DIALOGRC=${TOP_DIR}/dialogrc \
           dialog --clear \
-          --backtitle "Select a Module" \
-          --title "Available Modules" \
-          --menu "Choose a module:" 20 70 12 \
+          --backtitle "Student: ${FIRSTNAME} ${LASTNAME} - Select the week/module" \
+          --title "(${TODAY}) - Hello ${FIRSTNAME} this is WEEK #${WEEK_NUMBER}" \
+          --menu "Choose a week/module (Use arrow keys or # and press Enter):" 25 70 12 \
           "${OPTIONS[@]}" \
           2>&1 > /dev/tty )
 
@@ -112,4 +133,5 @@ main() {
 	done
 	clear
 }
+
 main
